#!/usr/bin/env bash
# Install and configure nginx

# update and install
sudo apt-get -y update
sudo apt-get install nginx

# start nginx
sudo service nginx start

# Allow nginx by listening on port 80
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

# Restarting nginx
sudo service nginx restart
