#!/usr/bin/env bash
# configure nginx to redirect to another page using /redirect_me

# update and install
sudo apt-get -y update
sudo apt-get install nginx

# start nginx
sudo service nginx start

# Allow nginx by listening on port 80
sudo ufw allow 'Nginx HTTP'

echo 'Hello World!' | sudo tee /var/www/html/index.html

# Redirection configarations
sudo sed -i '/server_name _;/a \        location /redirect_me { \            return 301 https://github.com/TKaburu; \        }' /etc/nginx/sites-enabled/default

# Restarting nginx
sudo service nginx restart

