#!/usr/bin/env bash
# Creates file /var/run/myscript.pid containing its PID, Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal, Displays Y U no love me?! when receiving a SIGINT signal

file=/var/run/myscript.pid
echo $$ > "$file"

until false
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm $file; exit' SIGQUIT
	trap 'echo I hate the kill command; rm $file; exit' SIGTERM
done
