#!/usr/bin/env bash
# Writes I am alive! to the file /tmp/my_process  and in between every I am alive! message, the program pauses for 2 seconds

until false
do
	echo "I am alive!" >> /tmp/my_process
    	sleep 2
done
