#!/usr/bin/env bash
# Displays fizzbuzz  when the number is a multiple of 3 and 5,  when the number is a multiple of 3 and 5,
# Buzz when the number is a multiple of 5, otherwise display numbers 1-100

count=1
while [ $count -le 100 ]
do
	if [ $((count%15)) = 0 ]
	then
		echo "FizzBuzz"  
	elif [ $((count%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((count%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$count"
	fi
	((count=count+ 1))
done
