#!/usr/bin/env bash
# Displays Best School 10 times but on the 9th dispay Hi

count=0
while [ $count -le 9 ]
do
	if [ $count -eq 9 ]
		then
			echo "Hi"
	fi

	echo "Best School"
	count=$((count+1))
done
