#!/usr/bin/env bash
# Displays information about a ile named school

filename="school"

if [ -e "$file" ]
	then
		echo "school file exists"
	if [ -e $file ]
		then
			echo "school file is not empty"
	if [ -f "$file" ]
		then
			echo "school is a regular file"
	fi
	else
		echo "school file is empty"
	fi
else
	echo "school file does not exist"
fi
