#!/usr/bin/env bash
# installing ufw firewall and set up rules on web-01

# update and install
sudo apt-get -y update
sudo apt-get -y install ufw

# first deny incoming trafic
sudo ufw default deny incoming

# Allow required ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#enable ufw so that configurations take place
sudo ufw enable
